### ISSUE TITLE
Add-on startup failed with mot recent Anki software update

### ISSUE THREAD

**Issue by todayshelearned** [mentheosis/anki-scanner-chinese-redux#19]
**Describe the bug**
Add-On Startup Failed

***Dubug Information at the bottom*****

**To Reproduce**
1. Upload Anki software to most recent software update
2. Relaunch Anki
3. See error

**Expected behavior**
I expected the add on to not fail

**Screenshots**

**Specs (please complete the following information):**
 - OS: iOS Sonoma 14.2.1
 - Anki Version ⁨23.12.1 (1a1d4d54)⁩
- Anki Scanner version last updated on Updated 2020-06-28.

**Additional context**

DEBUG INFO:

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.2.1-arm64-arm-64bit

When loading Chinese-Text-Scanner:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/kaseyjustus/Library/Application Support/Anki2/addons21/2121493325/__init__.py", line 23, in <module>
    from . import main
  File "/Users/kaseyjustus/Library/Application Support/Anki2/addons21/2121493325/main.py", line 24, in <module>
    from .gui import load_menu, unload_menu
  File "/Users/kaseyjustus/Library/Application Support/Anki2/addons21/2121493325/gui.py", line 21, in <module>
    from PyQt5.QtGui import QKeySequence
ImportError: dlopen(/Users/kaseyjustus/Library/Application Support/Anki2/addons21/2121493325/lib/PyQt5/QtGui.abi3.so, 0x0002): tried: '/Users/kaseyjustus/Library/Application Support/Anki2/addons21/2121493325/lib/PyQt5/QtGui.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/kaseyjustus/Library/Application Support/Anki2/addons21/2121493325/lib/PyQt5/QtGui.abi3.so' (no such file), '/Users/kaseyjustus/Library/Application Support/Anki2/addons21/2121493325/lib/PyQt5/QtGui.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by mentheosis** [comment]
the error you are seeing is similar to this one: https://stackoverflow.com/questions/65901162/how-can-i-run-pyqt5-on-my-mac-with-m1chip-ppc64el-architecture

there is a file in Qt (the graphical display component) that was prepared for an intel mac, but you are running on one of the new apple M arm chips. You might be able to follow the steps in the above stackoverflow to install the arm version Qt on your mac, and that may allow the addon to work. Otherwise we'd have to get an M1 mac to package up an arm version of this addon from the code here.

Let me know if you are able to try installing Qt per the link above
